version: "3.7"

services:
  app:
    build:
      context: ./
    ports:
      - "9122:9122"
    stop_signal: SIGINT
    environment:
      USERS_DATABASE: "database"

  database:
    image: mongo:5.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "coin-hunt"
      MONGO_INITDB_ROOT_PASSWORD: "coin-hunt-auth"
      MONGO_INITDB_DATABASE: "users-db"
    ports:
      - "27021:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
